DUANCANHAN_PHU/Models/Actor.cs
using System.ComponentModel.DataAnnotations;

namespace DUANMVC.Models
{
    public class Actor
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Profile  Picture  Url")]
        public string ProfilePictureUrl { get; set; }


        [Display(Name = "Full Name")]
        public string FullName { get; set; }

        [Display(Name = "Bio")]
        public string Bio { get; set; }

        //Mối liên hệ 

        public List<Actor_Movie> Actor_Movies { get; set; }


    }
}

DUANCANHAN_PHU/Models/Actor_Movie.cs
namespace DUANMVC.Models
{
    public class Actor_Movie
    {

        public int MovieId { get; set; }

        public Movie Movie { get; set; }

        public int ActorId { get; set; }
        public Actor Actor { get; set; }


    }
}

DUANCANHAN_PHU/Models/Cinema.cs
using System.ComponentModel.DataAnnotations;

namespace DUANMVC.Models
{
    public class Cinema
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "Logo Cinema")]
        public string Logo { get; set; }
        [Display(Name = "Name Cinema")]
        public string Name { get; set; }

        [Display(Name = "Description Cinema")]
        public string Description { get; set; }

        //Mối quan hệ 
        public List<Movie> Movies { get; set; }
    }
}

DUANCANHAN_PHU/Models/ErrorViewModel.cs
namespace DUANMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DUANCANHAN_PHU/Models/Movie.cs
using DUANCANHAN_PHU.Data.Enum;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DUANMVC.Models
{
    public class Movie
    {
        [Key]
        public int Id { get; set; }

        public string Name { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public string ImageUrl { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public MovieCategory MovieCategory { get; set; }

        //Mối liên hệ 


        public List<Actor_Movie> Actor_Movies { get; set; }






        public int CinemaId { get; set; }
        [ForeignKey("CinemaId")]
        public Cinema Cinema { get; set; }


        public int ProducerId { get; set; }
        [ForeignKey("ProducerId")]
        public Producer Producer { get; set; }







    }
}

DUANCANHAN_PHU/Models/Producer.cs
using System.ComponentModel.DataAnnotations;

namespace DUANMVC.Models
{
    public class Producer
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Profile  Picture  Url")]
        public string ProfilePictureUrl { get; set; }

        [Display(Name = "Full Name")]
        public string FullName { get; set; }

        [Display(Name = "Bio")]
        public string Bio { get; set; }


        //Mối quan hệ 

        public List<Movie> Movies { get; set; }
    }
}

DUANCANHAN_PHU/Controllers/ActorsController.cs
using DUANCANHAN_PHU.Data.Servies;
using DUANMVC.Data;
using Microsoft.AspNetCore.Mvc;

namespace DUANCANHAN_PHU.Controllers
{
    public class ActorsController : Controller
    {
        private readonly IActorsService _service;
        public ActorsController(IActorsService service)
        {
            _service = service;
        }



        //phương thức không đồng bộ
        public async Task<IActionResult> ActorsViews()
        {
            var data = await _service.GetAll();

            return View(data);
        }

        public IActionResult Create()
        {
            return View();
        }
    }
}

DUANCANHAN_PHU/Controllers/CinemasController.cs
using DUANMVC.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DUANCANHAN_PHU.Controllers
{
    public class CinemasController : Controller
    {

        private readonly AppDbContext _context;
        public CinemasController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> CinemasViews()
        {

            var allCinemas = await _context.Cinemas.ToListAsync();

            return View(allCinemas);
        }
    }
}

DUANCANHAN_PHU/Controllers/MoviesController.cs
using DUANMVC.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DUANCANHAN_PHU.Controllers
{
    public class MoviesController : Controller
    {
        private readonly AppDbContext _context;
        public MoviesController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {

            var allMovies = await _context.Movies.Include(n => n.Cinema).OrderBy(n => n.Price).ToListAsync();

            return View(allMovies);
        }
    }
}

DUANCANHAN_PHU/Controllers/ProducersController.cs
using DUANMVC.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DUANCANHAN_PHU.Controllers
{
    public class ProducersController : Controller
    {
        private readonly AppDbContext _context;
        public ProducersController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> ProducersViews()
        {
            var allProducers = await _context.Producers.ToListAsync();

            return View(allProducers);
        }
    }
}

DUANCANHAN_PHU/Views/Actors/ActorsViews.cshtml
@model IEnumerable<Actor>


@{
    ViewData["Title"] = "Danh sách Actors";
}

<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">

            <thead>


                <tr>

                    <th>  @Html.DisplayNameFor(model => model.ProfilePictureUrl)</th>
                    <th>  @Html.DisplayNameFor(model => model.FullName)</th>
                    <th>  @Html.DisplayNameFor(model => model.Bio)</th>
                    <th>Actions</th>
                </tr>
            </thead>

            <tbody>

                @foreach (var item in Model)
                {

                    <tr>
                        <td class="align-middle">
                            <img class="rounded-circle" src="@item.ProfilePictureUrl" alt="@item.FullName" style="max-width:150px" />

                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelitem => item.FullName)
                        </td>

                        <td class="align-middle">
                            @Html.DisplayFor(modelitem => item.Bio)

                        </td>


                        <td class="align-middle">

                            <a class="btn btn-outline-primary">  <i class="bi bi-pencil-square"></i> Edit </a>
                            <a class="btn btn-outline-info">  <i class="bi bi-eye"></i> Details </a>
                            <a class="btn btn-danger text-white">  <i class="bi bi-trash"></i> Delete </a>
                        </td>

                    </tr>

                }


            </tbody>



        </table>
    </div>

</div>


<div style="position:fixed ;  right:25px;  bottom:25px;" class="text-white">

    <a asp-controller="Actors" asp-action="Create" class="btn btn-success"><i class="bi bi-plus-cirle"></i>Add New</a>
</div>

DUANCANHAN_PHU/Views/Actors/Create.cshtml
@model Actor

@{
    ViewData["Title"] = " Add a new Actor";
}

<div class="row">
    <div class=" col-md-8  offset-2">
        <p>
            <h1>Add  A NEW ACTORS </h1>
        </p>

        <div class="row">
            <div class=" col-md-8  offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"> </div>
                </form>


                <div class="form-group text-center">
                   <img  id="ProfilePicturePreview"/>
                </div>


                <div class="form-group">
                    <label asp-for="ProfilePictureUrl" class="control-label"></label>
                    <input asp-for="ProfilePictureUrl" class="form-control" />
                    <span asp-validation-for="ProfilePictureUrl" class="text-danger"></span>
                </div>



                <div class="form-group">
                    <label asp-for="FullName" class="control-label"></label>
                    <input asp-for="FullName" class="form-control" />
                    <span asp-validation-for="FullName" class="text-danger"></span>
                </div> 
                
                
                <div class="form-group">
                    <label asp-for="Bio" class="control-label"></label>
                    <input asp-for="Bio" class="form-control" />
                    <span asp-validation-for="Bio" class="text-danger"></span>
                </div>
                <div class="form-group">
                  <input type="submit" value="Create" class="btn btn-outline-success float-right" />
                  <a class="btn btn-outline-secondary" asp-action="ActorsViews">Hiển thị tất cả</a>
                </div>


            </div>
        </div>

    </div>

</div>

@section Scripts{
    <script>
        $("#ProfilePictureUrl").on("change", function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $(this).val();

        })
    </script>
}

DUANCANHAN_PHU/Views/Cinemas/CinemasViews.cshtml
@model IEnumerable<Cinema>


@{
    ViewData["Title"] = "Danh sách Cinama";
}

<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">

            <thead>


                <tr class="text-center">

                    <th>  @Html.DisplayNameFor(model => model.Logo)</th>
                    <th>  @Html.DisplayNameFor(model => model.Name)</th>
                    <th>  @Html.DisplayNameFor(model => model.Description)</th>
                    <th>Actions</th>
                </tr>
            </thead>

            <tbody>

                @foreach (var item in Model)
                {

                    <tr>
                        <td class="align-middle">
                            <img class="rounded-circle" src="@item.Logo" alt="@item.Name" style="max-width:150px" />

                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelitem => item.Name)
                        </td>

                        <td class="align-middle">
                            @Html.DisplayFor(modelitem => item.Description)

                        </td>


                        <td class="align-middle">

                            <a class="btn btn-outline-primary">  <i class="bi bi-pencil-square"></i> Edit </a>
                            <a class="btn btn-outline-info">  <i class="bi bi-eye"></i> Details </a>
                            <a class="btn btn-danger text-white">  <i class="bi bi-trash"></i> Delete </a>
                        </td>

                    </tr>

                }


            </tbody>



        </table>
    </div>

</div>

DUANCANHAN_PHU/Views/Movies/Index.cshtml
@model IEnumerable<Movie>


@{
    ViewData["Title"] = "Danh sách Phim";
}

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Name
                                    @*   @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                {
                                <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                                } *@
                                    <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.ImageUrl" width="100%" alt="@item.Name">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">@item.Description</p>
                            <p class="card-text"><b>Cinema: </b>@item.Cinema.Name</p>
                            <p class="card-text"><b>Category: </b>@item.MovieCategory</p>
                            <p class="card-text"><b>Start Date: </b>@item.StartDate.ToString("dd MMMM yyyy")</p>
                            <p class="card-text"><b>End Date: </b>@item.EndDate.ToString("dd MMMM yyyy")</p>
                            <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                                {
                                    <span class="badge bg-success text-white">AVAILABLE</span>
                                }
                                else if (DateTime.Now > item.EndDate)
                                {
                                    <span class="badge bg-danger text-white">EXPIRED</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">UPCOMING</span>
                                }
                            </p>

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right" asp-action="Details" asp-route-id="@item.Id">
                                    <i class="bi bi-eye-fill"></i> Show Details
                                </a>
                                <a class="btn btn-success text-white @((DateTime.Now > item.EndDate) ? "disabled" : "")"
                                   asp-controller="Orders"
                                   asp-action="AddItemToShoppingCart"
                                   asp-route-id="@item.Id">
                                    <i class="bi bi-cart-plus"></i> Add to Cart (Price @item.Price.ToString("c"))
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

DUANCANHAN_PHU/Views/Producers/ProducersViews.cshtml
@model IEnumerable<Producer>


@{
    ViewData["Title"] = "Danh sách Producers";
}

<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">

            <thead>


                <tr class="text-center">

                    <th>  @Html.DisplayNameFor(model => model.ProfilePictureUrl)</th>
                    <th>  @Html.DisplayNameFor(model => model.FullName)</th>
                    <th>  @Html.DisplayNameFor(model => model.Bio)</th>
                    <th>Actions</th>
                </tr>
            </thead>

            <tbody>

                @foreach (var item in Model)
                {

                    <tr>
                        <td class="align-middle">
                            <img class="rounded-circle" src="@item.ProfilePictureUrl" alt="@item.FullName" style="max-width:150px" />

                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelitem => item.FullName)
                        </td>

                        <td class="align-middle">
                            @Html.DisplayFor(modelitem => item.Bio)

                        </td>


                        <td class="align-middle">

                            <a class="btn btn-outline-primary">  <i class="bi bi-pencil-square"></i> Edit </a>
                            <a class="btn btn-outline-info">  <i class="bi bi-eye"></i> Details </a>
                            <a class="btn btn-danger text-white">  <i class="bi bi-trash"></i> Delete </a>
                        </td>

                    </tr>

                }


            </tbody>



        </table>
    </div>

</div>

DUANCANHAN_PHU/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eTickets</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Movies" asp-action="Index">eTickets</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index"><i class="bi bi-film"></i> Movies</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="bi bi-gear"></i> Quản Lý
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Cinemas" asp-action="CinemasViews"><i class="bi bi-camera-reels"></i> Cinemas</a>
                                <a class="dropdown-item" asp-controller="Producers" asp-action="ProducersViews"><i class="bi bi-headset"></i> ProducersViews</a>
                                <a class="dropdown-item" asp-controller="Actors" asp-action="ActorsViews"><i class="bi bi-person-square"></i> Actors</a>
                            </div>
                        </li>
                    </ul>

                    <form class="form-inline my-2 my-lg-0" asp-controller="Movies" asp-action="Filter" style="padding-right: 25px;"> 
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a movie..." aria-label="Recipient's username" aria-describedby="button-addon2">    <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                   </form>

              

                 
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - eTickets
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>